# Generated by Django 4.1.7 on 2023-02-25 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 25, 22, 12, 26, 123965)
            ),
        ),
    ]
