# Generated by Django 4.1.7 on 2023-02-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(name="product", options={"ordering": ["-id"]},),
    ]
